### ISSUE TITLE
API not running on port 3000

### ISSUE THREAD

**Issue by moaazsidat** [jambonz/jambonz-infrastructure#6]
I'm currently trying to get the local docker setup for jambonz working, and running into a login error on the web app. Upon further inspection, it seems like nothing is running on port `3000`, whereas the web app is trying to make a call to `127.0.0.1:3000/v1/login`

Attaching a screenshot of the instantiation, any help would be much appreciated!
 
<img width="489" alt="Screen Shot 2021-01-18 at 2 28 14 PM" src="https://user-images.githubusercontent.com/5963656/104956279-d0083800-5999-11eb-833f-3c5ca2612065.png">

P.S. Thanks for putting this together! Undoubtedly one of the most well documented setup I've come along as it relates to calling / communications infrastructure.

**Comment by davehorton** [comment]
hmm, the jambonz-api-server container is the one that will be listening on port 3000.  That is exposed / mapped to the host machine as port 3000.  Are you running everything on your laptop?  If so, this should work.  If you are not running it all on your laptop then I think the problem may be the value you put in for HOST_IP in your .env file.  What did you put there?

**Comment by moaazsidat** [comment]
Correct, running everything on my laptop. 
Have `HOST_IP=127.0.0.1`

**Comment by davehorton** [comment]
then it should be working. Can you verify the jambonz-api-server container is running?  What is the output of `docker ps -a`

**Comment by moaazsidat** [comment]
Hmm, yep, that seems be to be running, just adding a screenshot of the UI:
![Screen Shot 2021-01-19 at 9 40 05 AM](https://user-images.githubusercontent.com/5963656/105049234-6f7d0780-5a3a-11eb-9a42-72f0e3077503.png)

**Comment by moaazsidat** [comment]
Hmm, definitely see something's off with `logging`

```
docker logs -f docker_api-server_1

> jambonz-api-server@1.1.0 start /usr/src/app
> node app.js

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/usr/src/app/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
/usr/src/app/node_modules/config/lib/config.js:182
    throw new Error('Configuration property "' + property + '" is not defined');
    ^

Error: Configuration property "logging" is not defined
    at Config.get (/usr/src/app/node_modules/config/lib/config.js:182:11)
    at Object.<anonymous> (/usr/src/app/app.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jambonz-api-server@1.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jambonz-api-server@1.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-19T15_29_20_710Z-debug.log
```

**Comment by davehorton** [comment]
ah, my bad.  This is an older version of jambonz-api-server.  I had forgotten to set up a build configuration on docker hub so it rebuilds with each checkin.

Can you pull the latest and retest?
```
docker pull jambonz/jambonz-api-server:latest
```
Immediately after starting, the logs should show this is version 1.20:
```
 docker logs -f docker_api-server_1

> jambonz-api-server@1.2.0 start
> node app.js

{"level":30, "time": "2021-01-19T17:30:13.396Z","pid":19,"hostname":"baec52a392f5","msg":"listening for HTTP traffic on port 3000","v":1}
```

**Comment by moaazsidat** [comment]
Amazing, that did the trick! Thanks! 🙌

**Comment by davehorton** [comment]
use

docker pull jambonz/api-server:latest


On Feb 15, 2022, at 10:25 AM, Eric Ravelo ***@***.***> wrote:


Hello @davehorton <https://github.com/davehorton>
Any reason why I am getting this now?

docker pull jambonz/jambonz-api-server:latest

Error response from daemon: pull access denied for jambonz/jambonz-api-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by ptd-31** [comment]
Hello @davehorton . I have installed SBC-Server with doc(Step F): https://www.jambonz.org/docs/open-source/self-host/
Before i installed MySQL and Redis-Server. But to step login. I can't login my defaut account on Web with http://my-address-server:3001/. I reset my password defaut: admin/admin with script(JAMBONES_MYSQL_HOST=localhost JAMBONES_MYSQL_USER=admin JAMBONES_MYSQL_PASSWORD=JambonzR0ck$ JAMBONES_MYSQL_DATABASE=jambones /home/admin/apps/jambonz-api-server/db/reset_admin_password.js), All informations of MySQL and path is right. But still can't login. In this case, How should I handle it?
