### ISSUE TITLE
JAMBONES_SBCS not found in file jambonz-scalable-production.yaml ecosystem sed script for feature server

### ISSUE THREAD

**Issue by nitinpo-Kore** [jambonz/jambonz-infrastructure#76]
@davehorton as check with hoan unable to find JAMBONES_SBCS parameter in file jambonz-scalable-production.yaml
 ecosystem sed script for feature server.. As these was not there in redis fs ently was not getting added after upgrade.

**Comment by davehorton** [comment]
@nitinpo-Kore @xquanluu This parameter is intentionally not there in the scalable cloudformation.  SBCs are dynamically discovered by means of SNS notifications.

**Comment by davehorton** [comment]
If you added JAMBONES_SBCS to the ecosystem for a scalable cluster that is a mistake and you should remove it and do a proper investigation

**Comment by nitinpo-Kore** [comment]
thanks for your reply we have done for mini but i have asked hoan for cluster so he told me that so for confirmation asked you.i hope for cluster its UpToDate.

**Comment by davehorton** [comment]
https://github.com/jambonz/jambonz-feature-server/blob/1477605e66b4168d198e19baaa22b155d1a1a37b/lib/utils/sbc-pinger.js#L142

That is how the feature server monitors SBCs in a cluster.  Not with the JAMBONES_SBCS env var
